export const MODELS = {
    CLASS_ROLES_MODEL: "CLASS_ROLES_MODEL",
    CLASSES_MODEL: "CLASSES_MODEL",
    REPORT_ENTITIES_MODEL: "REPORT_ENTITIES_MODEL",
    REPORTS_MODEL: "REPORTS_MODEL",
    USERS_MODEL: "USERS_MODEL"
};
