export const REPOSITORIES = {
    CLASS_ROLES_REPOSITORY: "CLASS_ROLES_REPOSITORY",
    CLASSES_REPOSITORY: "CLASSES_REPOSITORY",
    REPORT_ENTITIES_REPOSITORY: "REPORT_ENTITIES_REPOSITORY",
    REPORTS_REPOSITORY: "REPORTS_REPOSITORY",
    USERS_REPOSITORY: "USERS_REPOSITORY"
};
